[workspace]
members = [
  "zsplit",
  "zsplit-cli",
]
resolver = "2"

[workspace.package]
authors = ["zSchoen <dev@zschoen.dev>"]
readme = "README.md"
homepage = "https://zschoen.dev/projects/zsplit"
repository = "https://github.com/TheAlgorythm/zsplit"

[profile.release]
lto = "thin"
