name: Add Package Info on Dependabot PR

on:
  pull_request:
    types: [opened]
    branches:
      - MAIN

permissions:
  contents: write
  pull-requests: write

jobs:
  add-package-info:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')  && contains(github.event.pull_request.labels.*.name, 'rust')

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract package name and version
        id: extract_package
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          read PACKAGE_NAME OLD_VERSION NEW_VERSION < <(echo "${{ github.event.pull_request.title }}" | sed -E 's/^Bump ([^ ]+) from ([^ ]+) to ([^ ]+)$/\1 \2 \3/')
          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
          echo "OLD_VERSION=${OLD_VERSION}" >> $GITHUB_ENV
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc

      - name: Get package dependencies
        id: get_package_deps
        run: |
          PACKAGE_DEPS=$(cargo tree --package ${PACKAGE_NAME}@${NEW_VERSION} --quiet --target all)
          echo "package_deps<<EOF" >> $GITHUB_OUTPUT
          echo "${PACKAGE_DEPS}" | tee -a $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          PACKAGE_INV_DEPS=$(cargo tree --invert ${PACKAGE_NAME}@${NEW_VERSION} --quiet --target all)
          echo "package_inv_deps<<EOF" >> $GITHUB_OUTPUT
          echo "${PACKAGE_INV_DEPS}" | tee -a $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR with package info
        uses: actions/github-script@v7
        with:
          script: |
            const deps_info =`${{ steps.get_package_deps.outputs.package_deps }}`;
            const inv_deps_info = `${{ steps.get_package_deps.outputs.package_inv_deps }}`;
            const prNumber = context.payload.pull_request.number;
            const message = `### Additional Package Information\n\n<details><summary>Depends on</summary>\n\n\`\`\`txt\n${inv_deps_info}\n\`\`\`\n\n</details>\n\n<details><summary>Dependencies</summary>\n\n\`\`\`txt\n${deps_info}\n\`\`\`\n\n</details>`;
            await github.rest.pulls.createReview({
              ...context.repo,
              pull_number: prNumber,
              body: message,
              event: 'COMMENT'
            });
